baseURL = '/'
relativeURLs = false
languageCode = 'en-us'
title = 'Association for Constraint Programming'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    env = 'production'
    description = 'Association for Constraint Programming (ACP)'
    author = 'ACP'
    
    [params.label]
        text = "Association for Constraint Programming"
        icon = "/sites/default/files/acp-small-color-logo.jpg"
        iconHeight = 40

    # PaperMod specific options
    ShowReadingTime = false
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true

    
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about-the-acp"
    name = "About the ACP"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "history-of-the-acp"
    parent = "about-the-acp"
    name = "History of the ACP"
    url = "/about"
    weight = 30

  [[menu.main]]
    identifier = "policies"
    parent = "about-the-acp"
    name = "Policies"
    url = "/policies"
    weight = 40

  [[menu.main]]
    identifier = "anti-harassment"
    parent = "policies"
    name = "Anti-Harassment"
    url = "/events/anti-harassment-policy"
    weight = 50

  [[menu.main]]
    identifier = "diversity-equity-and-inclusion"
    parent = "policies"
    name = "Diversity, Equity and Inclusion"
    url = "/policies/diversity_equity_inclusion"
    weight = 60

  [[menu.main]]
    identifier = "cp-conference-organisation"
    parent = "policies"
    name = "CP Conference Organisation"
    url = "/policies/cp_conference_organisation"
    weight = 70

  [[menu.main]]
    identifier = "legal-information"
    parent = "about-the-acp"
    name = "Legal Information"
    url = "/about/legal_information"
    weight = 80

  [[menu.main]]
    identifier = "statutes-of-the-acp-english-version"
    parent = "legal-information"
    name = "Statutes of the ACP (English version)"
    url = "/about/statutes_en"
    weight = 90

  [[menu.main]]
    identifier = "statutes-of-the-acp"
    parent = "legal-information"
    name = "Statutes of the ACP"
    url = "/about/statutes"
    weight = 100

  [[menu.main]]
    identifier = "bylaws-of-the-acp"
    parent = "legal-information"
    name = "Bylaws of the ACP"
    url = "/about/bylaws"
    weight = 110

  [[menu.main]]
    identifier = "executive-committee"
    parent = "about-the-acp"
    name = "Executive Committee"
    url = "/about/committee"
    weight = 120

  [[menu.main]]
    identifier = "current-committee"
    parent = "executive-committee"
    name = "Current Committee"
    url = "/about/committee"
    weight = 130

  [[menu.main]]
    identifier = "elections"
    parent = "executive-committee"
    name = "Elections"
    url = "/about/committee/election-results"
    weight = 140

  [[menu.main]]
    identifier = "2026-election"
    parent = "elections"
    name = "2026 Election"
    url = "/about/committee/election-results/elect_results_2026"
    weight = 150

  [[menu.main]]
    identifier = "2024-election-results"
    parent = "elections"
    name = "2024 Election Results"
    url = "/about/committee/election-results/elect_results_2024"
    weight = 160

  [[menu.main]]
    identifier = "2022-election-results"
    parent = "elections"
    name = "2022 Election Results"
    url = "/about/committee/election-results/elect_results_2022"
    weight = 170

  [[menu.main]]
    identifier = "2020-election-results"
    parent = "elections"
    name = "2020 Election Results"
    url = "/about/committee/election-results/elect_results_2020"
    weight = 180

  [[menu.main]]
    identifier = "2018-election-results"
    parent = "elections"
    name = "2018 Election Results"
    url = "/about/committee/election-results/elect_results_2018"
    weight = 190

  [[menu.main]]
    identifier = "2016-election-results"
    parent = "elections"
    name = "2016 Election Results"
    url = "/about/committee/election-results/elect_results_2016"
    weight = 200

  [[menu.main]]
    identifier = "2014-election-results"
    parent = "elections"
    name = "2014 Election Results"
    url = "/about/committee/election-results/elect_results_2014"
    weight = 210

  [[menu.main]]
    identifier = "2012-election-results"
    parent = "elections"
    name = "2012 Election Results"
    url = "/about/committee/election-results/elect_results_2012"
    weight = 220

  [[menu.main]]
    identifier = "2010-election-results"
    parent = "elections"
    name = "2010 Election Results"
    url = "/about/committee/election-results/elect_results_2010"
    weight = 230

  [[menu.main]]
    identifier = "2008-election-results"
    parent = "elections"
    name = "2008 Election Results"
    url = "/about/committee/election-results/elect_results_2008"
    weight = 240

  [[menu.main]]
    identifier = "2007-election-results"
    parent = "elections"
    name = "2007 Election Results"
    url = "/about/committee/election-results/elect_results_2007"
    weight = 250

  [[menu.main]]
    identifier = "2006-election-results"
    parent = "elections"
    name = "2006 Election Results"
    url = "/about/committee/election-results/elect_results_2006"
    weight = 260

  [[menu.main]]
    identifier = "2005-election-results"
    parent = "elections"
    name = "2005 Election Results"
    url = "/about/committee/election-results/elect_results_2005"
    weight = 270

  [[menu.main]]
    identifier = "2004-election-results"
    parent = "elections"
    name = "2004 Election Results"
    url = "/about/committee/election-results/elect_results_2004"
    weight = 280

  [[menu.main]]
    identifier = "2003-election-results"
    parent = "elections"
    name = "2003 Election Results"
    url = "/about/committee/election-results/elect_results_2003"
    weight = 290

  [[menu.main]]
    identifier = "quarterly-reports-decisions"
    parent = "executive-committee"
    name = "Quarterly Reports / Decisions"
    url = "/about/committee/decisions"
    weight = 300

  [[menu.main]]
    identifier = "general-assembly-reports"
    parent = "about-the-acp"
    name = "General Assembly reports"
    url = "/about/general-assembly-archive"
    weight = 310

  [[menu.main]]
    identifier = "sponsorships-donations"
    parent = "about-the-acp"
    name = "Sponsorships & Donations"
    url = "/sponsorships-donations"
    weight = 320

  [[menu.main]]
    identifier = "acp-logo"
    parent = "about-the-acp"
    name = "ACP Logo"
    url = "/about/acp-logo"
    weight = 330

  [[menu.main]]
    identifier = "constraints-journal"
    name = "Constraints Journal"
    url = "/cj2"
    weight = 340

  [[menu.main]]
    identifier = "constraint-programming"
    name = "Constraint Programming"
    url = "/about/community-links"
    weight = 350

  [[menu.main]]
    identifier = "resources"
    parent = "constraint-programming"
    name = "Resources"
    url = "/about/community-links"
    weight = 360

  [[menu.main]]
    identifier = "solvers"
    parent = "constraint-programming"
    name = "Solvers"
    url = "/cp/solvers"
    weight = 370

  [[menu.main]]
    identifier = "acp-success-stories"
    parent = "constraint-programming"
    name = "ACP Success Stories"
    url = "/cp/success-stories"
    weight = 380

  [[menu.main]]
    identifier = "publication-venues"
    parent = "constraint-programming"
    name = "Publication Venues"
    url = "/cp/publication-venues"
    weight = 390

  [[menu.main]]
    identifier = "cp-and-cpaior-papers"
    parent = "constraint-programming"
    name = "CP and CPAIOR Papers"
    url = "/cp/application/papers"
    weight = 400

  [[menu.main]]
    identifier = "phd-thesis-archive"
    parent = "constraint-programming"
    name = "PhD Thesis Archive"
    url = "/theses"
    weight = 410

  [[menu.main]]
    identifier = "career-news"
    parent = "constraint-programming"
    name = "Career News"
    url = "/news/career-news"
    weight = 420

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/cp-conference-series"
    weight = 430

  [[menu.main]]
    identifier = "cp-conference-series"
    parent = "events"
    name = "CP Conference Series"
    url = "/events/cp-conference-series"
    weight = 440

  [[menu.main]]
    identifier = "acp-summer-schools"
    parent = "events"
    name = "ACP Summer Schools"
    url = "/events/summer-schools"
    weight = 450

  [[menu.main]]
    identifier = "competitions"
    parent = "events"
    name = "Competitions"
    url = "/events/competitions"
    weight = 460

  [[menu.main]]
    identifier = "call-for-outreach-initiatives"
    parent = "events"
    name = "Call for Outreach Initiatives"
    url = "/events/outreach"
    weight = 470

  [[menu.main]]
    identifier = "awards"
    name = "Awards"
    url = "/awards/research-excellence-award"
    weight = 480

  [[menu.main]]
    identifier = "research-excellence-award"
    parent = "awards"
    name = "Research Excellence Award"
    url = "/awards/research-excellence-award"
    weight = 490

  [[menu.main]]
    identifier = "distinguished-service-award"
    parent = "awards"
    name = "Distinguished Service Award"
    url = "/awards/distinguished-service-award"
    weight = 500

  [[menu.main]]
    identifier = "early-career-researcher-award"
    parent = "awards"
    name = "Early Career Researcher Award"
    url = "/awards/early-career-research-award"
    weight = 510

  [[menu.main]]
    identifier = "doctoral-research-award"
    parent = "awards"
    name = "Doctoral Research Award"
    url = "/awards/doctoral-research-award"
    weight = 520

  [[menu.main]]
    identifier = "paper-awards"
    parent = "awards"
    name = "Paper Awards"
    url = "/awards/paper-awards"
    weight = 530

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 540
